apiVersion: v1
kind: Pod
metadata:
  name: pod-mlflow
spec:
  containers:
  - name: mlflow
    image: mlflow
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"